language: cpp

compiler: gcc

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 
install:
 - sudo apt-get install -qq cmake
 - sudo apt-get install -qq g++-4.9
 - export CXX="g++-4.9"

before_script:
 - mkdir -p build
 - cd build

script:
 - cmake ..
 - make
 - "./nid-test"
 - "./fabric-test"
 - "./harc-test"
 - "./query-test"
