language: cpp

compiler: gcc

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test -y
 - sudo add-apt-repository -y ppa:smspillaz/cmake-2.8.12 -y
 - sudo apt-get update -qq
 
install:
 - sudo apt-get install -qq cmake-2.8.12
 - sudo apt-get install -qq g++-4.9
 - sudo apt-get install -qq cppcheck
 - sudo apt-get install -qq gtkmm-3.0-dev
 - export CXX="g++-4.9"

before_script:
 - mkdir -p build
 - cd build

script:
 - cmake ..
 - make
 - make tests
 - "./nid-unit"
 - "./def-unit"
 - "./harc-unit"
 - "./fabric-unit"
 - cppcheck -I../daemon/includes --error-exitcode=2 ../daemon/src
 - ../tools/cpplint.py --filter=-whitespace/braces,-whitespace/tab,-build/c++11,-runtime/int,-runtime/references --extensions=hpp,cpp ../daemon/src/* ../daemon/includes/fdsb/*
