language: cpp

compiler: gcc

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

install:
 - sudo apt-get install -qq g++-4.8

before_script:
 - mkdir -p build
 - cd build

script:
 - cmake ..
 - make
 - "./nid-test"
 - "./fabric-test"
 - "./harc-test"
 - "./query-test"
